[
  {
    "title": "",
    "organization": "",
    "location": "Los Angeles County (SFV area included)",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "Job / Paid Work Experience",
    "notes": "Good starter job, builds skills and resume"
  },
  {
    "title": "",
    "organization": "",
    "location": "Los Angeles County",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "Internship",
    "notes": "Exposure to many fields"
  },
  {
    "title": "",
    "organization": "",
    "location": "Los Angeles",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "Internship / Leadership",
    "notes": "Includes mentor and company exposure"
  },
  {
    "title": "",
    "organization": "",
    "location": "Los Angeles / LAUSD",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "Job training / Internship",
    "notes": "Local, structured, offers credit"
  },
  {
    "title": "",
    "organization": "",
    "location": "California (state‑wide)",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "Training / Job‑search / Coaching",
    "notes": "Great if you want guidance and help finding work later on!"
  },
  {
    "title": "",
    "organization": "",
    "location": "Sylmar, CA",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "Volunteer / Part‑time / Enrichment",
    "notes": "Good for leadership + experience"
  },
  {
    "title": "",
    "organization": "",
    "location": "Mission / Sylmar area",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "Internship / Training",
    "notes": "Great for STEM interests"
  },
  {
    "title": "",
    "organization": "",
    "location": "",
    "remote": "",
    "eligibility": "",
    "pay": "",
    "deadline": "",
    "link": "",
    "contact": "",
    "type": "",
    "notes": ""
  }
]
